version: "3.9"
services:
  bot_api:
    build: ../bot_api
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - bot_api_data:/var/lib/bot_api
  admin_panel:
    build: ../admin_panel
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/login/"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - admin_media:/app/media
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
volumes:
  bot_api_data:
  admin_media:
  qdrant_data:
