services:
  bot_api:
    build: ../bot_api
    ports: ["8000:8000"]
    depends_on: ["qdrant"]
    environment:
      # Если используете Lockbox на ВМ:
      - LOCKBOX_SECRET_ID=${LOCKBOX_SECRET_ID}
      # Фолбэк для локального запуска (если нет Lockbox):
      - DATABASE_DSN=${DATABASE_DSN}
      - AMO_BASE_URL=${AMO_BASE_URL:-https://amojo.amocrm.ru}
      - AMO_SCOPE_ID=${AMO_SCOPE_ID}
      - AMO_ACCOUNT_ID=${AMO_ACCOUNT_ID}
      - AMO_SECRET=${AMO_SECRET}
      - YFM_API_KEY=${YFM_API_KEY}
      - YFM_FOLDER_ID=${YFM_FOLDER_ID}
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=
      - KB_PATH=/app/kb_files
    volumes:
      - bot_api_data:/var/lib/bot_api

  admin_panel:
    build: ../admin_panel
    ports: ["8001:8000"]
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - BOT_API_URL=http://bot_api:8000
    volumes:
      - admin_media:/app/media
